# Generated by Django 5.2.17 on 2026-10-01 05:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'inventory_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Unique Stock Keeping Unit (e.g., SKU-1001)', max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current physical on-hand quantity')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Threshold below which item triggers low-stock alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Inventory.category')),
            ],
            options={
                'db_table': 'inventory_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RESTOCK', 'Restock (Add Stock)'), ('SALE', 'Sale (Deduct Stock)'), ('DAMAGE', 'Damage / Spoilage (Deduct Stock)'), ('RETURN', 'Customer Return (Add Stock)')], db_index=True, max_length=20)),
                ('quantity_delta', models.IntegerField(help_text='Signed stock difference (+50 for restock, -2 for sale)')),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Inventory.product')),
            ],
            options={
                'db_table': 'inventory_stock_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
