# Generated by Django 5.2.17 on 2026-10-03 11:08

from django.db import migrations, models


def convert_cashier_to_staff(apps, schema_editor):
    User = apps.get_model('Auth', 'User')
    User.objects.filter(role='CASHIER').update(role='STAFF')


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_cashier_to_staff, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Warehouse Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
    ]
