# Generated by Django 5.2.17 on 2026-10-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STAFF', 'Inventory Staff')], default='STAFF', max_length=20),
        ),
    ]
